import * as fs from 'fs';
import * as path from 'path';
import { BatchReportData, BatchKeywordResult } from '../types';
import { DemandRanker } from '../analyzers/demand-ranker';

export class BatchMarkdownReporter {
  private readonly ranker = new DemandRanker();

  generate(data: BatchReportData, outputPath: string): void {
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(outputPath, this.build(data), 'utf-8');
    console.log(`\nReport saved → ${outputPath}`);
  }

  private build(data: BatchReportData): string {
    const { keywords, source, subreddits, results, generatedAt } = data;
    const lines: string[] = [];

    // ── 标题 ──────────────────────────────────────────────────────────
    lines.push(`# Batch Demand Comparison Report`);
    lines.push('');
    lines.push(`| Field | Value |`);
    lines.push(`|-------|-------|`);
    lines.push(`| Keywords | ${keywords.map(k => `\`${k}\``).join(', ')} |`);
    lines.push(`| Platform | ${source} |`);
    lines.push(`| Subreddits | ${subreddits.length ? subreddits.join(', ') : '(all)' } |`);
    lines.push(`| Limit per keyword | ${data.limit} |`);
    lines.push(`| Generated at | ${generatedAt.toISOString().replace('T', ' ').slice(0, 19)} UTC |`);
    lines.push('');

    // ── 对比总表 ──────────────────────────────────────────────────────
    lines.push(`## Comparison Overview`);
    lines.push('');
    lines.push('| Keyword | Posts | Top Keywords (3) | Hottest Post | Avg Engagement |');
    lines.push('|---------|-------|------------------|--------------|----------------|');

    for (const result of results) {
      const postCount = result.analysis.totalPosts;
      const topKw = this.topKeywords(result, 3);
      const hottest = this.hottestPostTitle(result);
      const avgEng = this.avgEngagement(result);
      lines.push(`| \`${result.keyword}\` | ${postCount} | ${topKw} | ${hottest} | ${avgEng} |`);
    }
    lines.push('');

    // ── 各关键词详情 ──────────────────────────────────────────────────
    for (const result of results) {
      lines.push(`## ${result.keyword}`);
      lines.push('');

      // 词频 Top 10
      lines.push(`### Keyword Frequency Top 10`);
      lines.push('');
      lines.push('| Rank | Keyword | Count |');
      lines.push('|------|---------|-------|');
      let rank = 1;
      for (const [word, count] of result.analysis.keywords) {
        if (rank > 10) break;
        lines.push(`| ${rank++} | ${word} | ${count} |`);
      }
      lines.push('');

      // 热帖 Top 5
      const topPosts = result.analysis.topDemands.slice(0, 5);
      lines.push(`### Hot Posts Top ${topPosts.length}`);
      lines.push('');
      lines.push('> Engagement = upvotes + comments × 2');
      lines.push('');

      topPosts.forEach((post, i) => {
        const score = this.ranker.engagementScore(post);
        lines.push(`**${i + 1}. ${post.title}**`);
        lines.push('');
        lines.push(`| Field | Value |`);
        lines.push(`|-------|-------|`);
        lines.push(`| Author | u/${post.author} |`);
        lines.push(`| Upvotes | ${post.score} |`);
        lines.push(`| Comments | ${post.commentCount} |`);
        lines.push(`| Engagement | **${score}** |`);
        lines.push(`| Date | ${post.createdAt.toISOString().slice(0, 10)} |`);
        lines.push(`| Link | [View post](${post.url}) |`);
        lines.push('');
      });

      lines.push('---');
      lines.push('');
    }

    lines.push(`*Generated by community-demand-collector (batch mode)*`);
    return lines.join('\n');
  }

  private topKeywords(result: BatchKeywordResult, n: number): string {
    const entries = [...result.analysis.keywords.entries()].slice(0, n);
    if (entries.length === 0) return '-';
    return entries.map(([w, c]) => `${w}(${c})`).join(', ');
  }

  private hottestPostTitle(result: BatchKeywordResult): string {
    if (result.analysis.topDemands.length === 0) return '-';
    const post = result.analysis.topDemands[0];
    const title = post.title.length > 40 ? post.title.slice(0, 37) + '…' : post.title;
    return title;
  }

  private avgEngagement(result: BatchKeywordResult): string {
    if (result.posts.length === 0) return '0';
    const total = result.posts.reduce((sum, p) => sum + this.ranker.engagementScore(p), 0);
    return (total / result.posts.length).toFixed(1);
  }
}
