import * as fs from 'fs';
import * as path from 'path';
import { ReportData } from '../types';
import { DemandRanker } from '../analyzers/demand-ranker';

export class MarkdownReporter {
  private readonly ranker = new DemandRanker();

  generate(data: ReportData, outputPath: string): void {
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(outputPath, this.build(data), 'utf-8');
    console.log(`\nReport saved → ${outputPath}`);
  }

  private build(data: ReportData): string {
    const { config, analysis, generatedAt } = data as ReportData & {
      charts?: { wordCloudUrl?: string; trendUrl?: string };
    };
    const lines: string[] = [];

    // ── 封面 ──────────────────────────────────────────────────────────
    lines.push(`# Community Demand Report`);
    lines.push('');
    lines.push(`| 字段 | 值 |`);
    lines.push(`|------|----|`);
    lines.push(`| 关键词 | \`${config.keyword}\` |`);
    lines.push(`| 平台 | ${config.source} |`);
    lines.push(`| 采集帖子数 | ${analysis.totalPosts} |`);
    lines.push(`| 生成时间 | ${generatedAt.toISOString().replace('T', ' ').slice(0, 19)} UTC |`);
    lines.push('');

    // ── 可视化 ────────────────────────────────────────────────────────
    if ((data as any).charts?.wordCloudUrl || (data as any).charts?.trendUrl) {
      lines.push('## 可视化图表');
      lines.push('');
      if ((data as any).charts?.wordCloudUrl) {
        lines.push(`![Keyword Cloud](${(data as any).charts.wordCloudUrl})`);
        lines.push('');
      }
      if ((data as any).charts?.trendUrl) {
        lines.push(`![Trend](${(data as any).charts.trendUrl})`);
        lines.push('');
      }
    }

    // ── 执行摘要 ──────────────────────────────────────────────────────
    lines.push(`## 执行摘要`);
    lines.push('');
    lines.push(analysis.summary);
    lines.push('');

    // ── 高频关键词 ────────────────────────────────────────────────────
    lines.push(`## 高频关键词 Top 20`);
    lines.push('');
    lines.push('| 排名 | 关键词 | 出现次数 |');
    lines.push('|------|--------|----------|');
    let rank = 1;
    for (const [word, count] of analysis.keywords) {
      if (rank > 20) break;
      lines.push(`| ${rank++} | ${word} | ${count} |`);
    }
    lines.push('');

    // ── 热度 Top 帖子 ─────────────────────────────────────────────────
    lines.push(`## 高热度帖子 Top ${analysis.topDemands.length}`);
    lines.push('');
    lines.push('> 热度得分 = 点赞数 + 评论数 × 2');
    lines.push('');

    analysis.topDemands.forEach((post, i) => {
      const score = this.ranker.engagementScore(post);
      lines.push(`### ${i + 1}. ${post.title}`);
      lines.push('');
      lines.push(`| 字段 | 值 |`);
      lines.push(`|------|----|`);
      lines.push(`| 作者 | u/${post.author} |`);
      lines.push(`| 点赞 | ${post.score} |`);
      lines.push(`| 评论 | ${post.commentCount} |`);
      lines.push(`| 热度得分 | **${score}** |`);
      lines.push(`| 发布日期 | ${post.createdAt.toISOString().slice(0, 10)} |`);
      lines.push(`| 链接 | [查看原帖](${post.url}) |`);
      lines.push('');

      lines.push('');

      if (post.titleZh) {
        lines.push(`**💡 中译标题：${post.titleZh}**`);
        lines.push('');
      }

      if (post.summaryZh) {
        lines.push(`> **深度摘要 (商务视角)**`);
        post.summaryZh.split('\n').forEach(line => {
          lines.push(`> ${line}`);
        });
        lines.push('');
      } else if (post.content.trim()) {
        const preview = post.content.replace(/\n+/g, ' ').trim().slice(0, 300);
        lines.push(`**内容摘要：**`);
        lines.push('');
        lines.push(`> ${preview}${post.content.length > 300 ? '…' : ''}`);
        lines.push('');
      }

      lines.push('---');
      lines.push('');
    });

    // ── 完整帖子列表 ──────────────────────────────────────────────────
    lines.push(`## 全部采集帖子`);
    lines.push('');
    lines.push('| # | 标题 | 作者 | 点赞 | 评论 | 日期 | 链接 |');
    lines.push('|---|------|------|------|------|------|------|');

    data.analysis.topDemands.forEach((post, i) => {
      const date = post.createdAt.toISOString().slice(0, 10);
      const title = post.title.length > 50 ? post.title.slice(0, 47) + '…' : post.title;
      lines.push(`| ${i + 1} | ${title} | u/${post.author} | ${post.score} | ${post.commentCount} | ${date} | [链接](${post.url}) |`);
    });

    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push(`*Generated by community-demand-collector*`);

    return lines.join('\n');
  }
}

